spring:
  application:
    name: Hooligans
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
    import: optional:file:.env[.properties]

#    pool:
#      enabled: true
#      max-size: 10
#      initial-size: 5
#      max-idle-time: 30s

#  datasource:
#    url: ${LOCAL_DB_URL}
#    username: ${LOCAL_DB_USERNAME}
#    password: ${LOCAL_DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.example.entity

---
spring:
  config:
    activate:
      on-profile: local

  r2dbc:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

#logging:
#  level:
#    org.springframework.security: DEBUG

kakao:
  client-id: ${KAKAO_REST_API_KEY}
  uri:
    auth-token: ${KAKAO_AUTH_TOKEN_URI}
    redirect: ${KAKAO_REDIRECT_URI}

jwt:
  secret-key: ${JWT_SECRET_KEY}
