spring:
  application:
    name: Hooligans
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_PAYMENT_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.entity